spring:
  cloud:
    gateway:
      routes:
#        - id: after_route
#          uri: http://localhost:8081/red/get
#          predicates:
#            - After=2017-01-20T17:42:47.789-07:00[America/Denver]
        - id: add_request_header_route
          uri: http://localhost:8081/red/get/{segment}
          predicates:
            - Path=/red/get/{segment}
          filters:
            - AddRequestHeader=X-Request-Red, Blue-{segment}